// Gulp! audio engine.
//
// MUSIC: eight licensed HydroGene loops (free for any use), one per world or mode. Each
// is fetched lazily from `music/<id>.m4a` (Vite serves public/ at the site root), decoded
// once, cached (small LRU), looped sample-accurately over [PAD, PAD + len) and
// crossfaded on every change. The files carry 0.25 s of the loop's own continuation on
// both ends, so the loop stays seamless whether or not a browser trims AAC priming.
//
// SFX: synthesized live in WebAudio (oscillators, filtered noise, FM). No samples and
// no generated media. Every tonal sound is tuned to the KEY of the current track, so the
// combo melody, chimes and fanfares always sit in key with the music.
//
// Mix (levels set for a phone speaker first, headphones second):
//   voice ─┬─► sfx bus ─► glue comp ─► makeup trim ───────┐
//          └─► reverb send ─► convolver ─► EQ ─► return ──┤
//   track ─► fade ─► music bus ─► duck ───────────────────┼─► master ─► limiter ─► trim ─► out
// Music files are -16 LUFS; the bus sits them near -21 LUFS so effects ride on top.
// The limiter is a safety net only (ceiling about -1.5 dBFS). Nothing should ever reach it.

// <generated by tools/audio_build.py: do not hand-edit>
// file: public/music/<id>.m4a. loop = [PAD, PAD + len) seconds. root = SFX key
// (pitch class of the track's relative-major tonic, C = 0); cents = tuning vs A440.
const MUSIC_PAD = 0.25;
const MUSIC = {
  peaceful_village: { len: 85.544667, root: 4, cents: 1.7, title: 'Peaceful Village', author: 'HydroGene' },
  holy_sanctuary: { len: 74.669646, root: 9, cents: 2.9, title: 'Holy Sanctuary', author: 'HydroGene' },
  traveling_the_sky: { len: 70.074313, root: 0, cents: -2.6, title: 'Traveling the Sky', author: 'HydroGene' },
  lively_city: { len: 64.616083, root: 0, cents: -0.9, title: 'Lively City', author: 'HydroGene' },
  long_journey: { len: 45.700896, root: 5, cents: 2.0, title: 'Long Journey', author: 'HydroGene' },
  spirits_forest: { len: 54.638396, root: 11, cents: 0.1, title: 'Spirits Forest', author: 'HydroGene' },
  east_town: { len: 58.776792, root: 0, cents: 1.5, title: 'East Town', author: 'HydroGene' },
  wood_forest_town: { len: 118.852688, root: 6, cents: -1.6, title: 'Wood Forest Town', author: 'HydroGene' },
};
const MUSIC_KEYS = {
  menu: 'peaceful_village', zen: 'holy_sanctuary', race: 'traveling_the_sky', bakery: 'lively_city',
  picnic: 'long_journey', playroom: 'spirits_forest', garden: 'east_town', beach: 'traveling_the_sky',
  kitchen: 'wood_forest_town', candy: 'lively_city', farm: 'long_journey', snow: 'holy_sanctuary',
  craft: 'wood_forest_town', fair: 'lively_city', space: 'traveling_the_sky',
  // aliases: old main.js keys and the town world
  calm: 'peaceful_village', play: 'lively_city', city: 'lively_city', title: 'peaceful_village', map: 'peaceful_village',
};
// </generated>

export { MUSIC_KEYS };

export const CREDITS = [
  'Music',
  '"Peaceful Village", "Holy Sanctuary", "Traveling the Sky", "Lively City", "Long Journey",',
  '"Spirits Forest", "East Town" and "Wood Forest Town" by HydroGene,',
  'from "28 High Quality 16-bit RPG Music" (hydrogene.itch.io).',
  'Sound effects synthesized in the game.',
].join('\n');

// ------------------------------------------------------------------ mix constants (dB)
const MUSIC_DB = -5;            // music bus: -16 LUFS files land near -21 LUFS
const TRACK_TRIM_DB = { holy_sanctuary: -1.5 }; // the beatless Zen pads sit back a touch
const SFX_DB = 0;
const XFADE = 1.4;              // world-to-world crossfade (equal power), seconds
const DECODED_CACHE = 3;        // decoded tracks kept in memory (about 30 MB each)
const RESUME_WITHIN = 45;       // re-entering a track within this many seconds resumes it
// SFX bus glue: gentle, only stacks of sounds reach it. Master: safety limiter.
const GLUE = { threshold: -12, knee: 6, ratio: 2.5, attack: 0.005, release: 0.15 };
const LIMIT = { threshold: -2, knee: 0, ratio: 20, attack: 0.001, release: 0.1 };

// Mixer: one fader per sound in dB (applied on the voice output). Calibrated with
// tools/audio_check.py against the in-game music bed (100 ms loudness, median -21 LUFS):
// small pops +3 dB over the bed, medium +6, big swallows +9, stings +3..+6 (and they duck
// the music), UI about -5, countdown -2 / +1 (urgent).
const FADER_DB = {
  pop: 0, gulp: -1, thump: 0, sparkle: 0, sizeUp: 3, target: 0, rimWobble: 4.5, tick: 4, tap: 1.2,
  uiOpen: 6, uiClose: 7, star: 0, win: 1.5, timeUp: 1.5, swallowedHole: 0, levelStart: 2,
  lastOne: 4.5, boosterMagnet: 0, boosterFreeze: 2.2, boosterGrow: 5, reward: 1.5,
};

// ------------------------------------------------------------------ pop dynamics
const POP_GAIN = 0.5;           // a small mid-combo pop peaks near -10 dBFS
const POP_STRUM = 0.036;        // simultaneous swallows become a quick run, not a chord
const POP_BACKLOG = 0.3;        // max look-ahead of the run; extra pops in a pile are skipped
const POP_VOICES = 8;           // concurrent pop voices; the oldest is faded out (stolen)

// ------------------------------------------------------------------ pitch
const PENTA = [0, 2, 4, 7, 9];  // major pentatonic: every note agrees with every other
const COMBO_LO = 71, COMBO_HI = 96; // combo melody window (B4..C7), ~11 notes in any key

const dbToGain = (d) => Math.pow(10, d / 20);
const clamp = (x, a, b) => Math.min(b, Math.max(a, x));
const fold = (f, hi) => { while (f > hi) f /= 2; return f; }; // octave-fold below a ceiling

// ------------------------------------------------------------------ materials
// Prop id -> material. Unknown ids fall back to keyword rules, then to 'plastic'.
// A prop may also carry its own `material` (or `sfx`) field, which wins.
const MATERIAL_OF = {
  // town (props.js)
  person: 'person', cone: 'plastic', hydrant: 'metal', bin: 'metal', pot: 'ceramic', mailbox: 'metal',
  sign: 'metal', lamp: 'metal', bush: 'soft', flowerbed: 'soft', bench: 'wood', bike: 'vehicle',
  vending: 'metal', booth: 'ceramic', cart: 'wood', car: 'vehicle', taxi: 'vehicle', van: 'vehicle',
  shelter: 'ceramic', tree: 'wood', pine: 'wood', kiosk: 'wood', fountain: 'ceramic', bus: 'vehicle',
  truck: 'vehicle', house: 'wood', shop: 'wood', apartment: 'ceramic', office: 'ceramic', tower: 'metal',
  // bakery
  sprinkle: 'crunchy', candy: 'crunchy', gumdrop: 'squishy', macaron: 'squishy', cookie: 'crunchy',
  donut: 'squishy', cupcake: 'squishy', croissant: 'crunchy', cakeslice: 'squishy', lollipop: 'crunchy',
  icecream: 'squishy', pie: 'squishy', cake: 'squishy', layercake: 'squishy', gingerhouse: 'crunchy',
  // picnic
  grape: 'fruit', cherry: 'fruit', strawberry: 'fruit', lemon: 'fruit', apple: 'fruit', orange: 'fruit',
  banana: 'fruit', grapes: 'fruit', juicebox: 'plastic', sandwich: 'squishy', melonslice: 'fruit',
  watermelon: 'fruit', blanketroll: 'soft', basket: 'wood', fruitcart: 'wood',
  // playroom
  block: 'wood', toyball: 'plastic', duck: 'plastic', crayon: 'crunchy', stackrings: 'plastic',
  rocket: 'plastic', toycar: 'plastic', robot: 'metal', locomotive: 'wood', traincar: 'wood',
  teddy: 'soft', rockinghorse: 'wood', dollhouse: 'wood', playcastle: 'plastic',
  // garden
  tulip: 'soft', daisy: 'soft', mushroom: 'squishy', gnome: 'ceramic', potplant: 'ceramic',
  birdhouse: 'wood', wateringcan: 'metal', pumpkin: 'fruit', hedge: 'soft', gardenbench: 'wood',
  gardenfountain: 'ceramic', gazebo: 'wood',
  // beach
  shell: 'ceramic', starfish: 'soft', bucket: 'plastic', spade: 'plastic', crab: 'person',
  parasol: 'soft', beachball: 'plastic', lifering: 'plastic', deckchair: 'wood', surfboard: 'plastic',
  sandcastle: 'crunchy', lifeguard: 'wood',
  // kitchen
  cup: 'ceramic', bottle: 'ceramic', jar: 'ceramic', mug: 'ceramic', platestack: 'ceramic',
  teapot: 'ceramic', toaster: 'metal', pan: 'metal', fruitbowl: 'ceramic', mixer: 'metal',
  fridge: 'metal', stove: 'metal',
};
// Fallback rules, first match wins (food and fruit before critters, so "hotdog" and
// "mango" don't turn into a person).
const MATERIAL_RULES = [
  [/car$|bus$|truck|van$|taxi|tractor|scooter|bike|moped/, 'vehicle'],
  [/cake|donut|pie$|bun$|bread|cream|jelly|pudding|muffin|sandwich|marshmallow|gum|mushroom|hotdog|burger/, 'squishy'],
  [/cookie|candy|cracker|chip|toast|pretzel|crisp|waffle|biscuit|crayon|sand/, 'crunchy'],
  [/apple|orange|banana|grape|berry|cherry|lemon|lime|melon|mango|peach|pear|plum|fruit|pumpkin|tomato|carrot/, 'fruit'],
  [/cup$|mug|plate|bowl|jar|bottle|vase|teapot|glass|pot$|gnome|shell|fountain/, 'ceramic'],
  [/pan$|kettle|spoon|fork|toaster|fridge|stove|oven|lamp|sign|metal|robot|bell|hydrant|tincan|canister/, 'metal'],
  [/bench|chair|table|box|crate|house|fence|tree|log$|basket|block|horse|barrel|train|wood/, 'wood'],
  [/teddy|plush|pillow|cushion|blanket|towel|bush|hedge|flower|tulip|daisy|rose|grass|leaf|starfish/, 'soft'],
  [/person|kid|dog|cat$|kitten|puppy|bird|crab|frog|bunny|chick|critter/, 'person'],
];
export const MATERIALS = ['soft', 'squishy', 'crunchy', 'plastic', 'wood', 'metal', 'ceramic', 'fruit', 'person', 'vehicle'];
export function materialOf(prop) {
  if (!prop) return 'plastic';
  const own = prop.material || prop.sfx;
  if (own && MATERIALS.includes(own)) return own;
  const id = String(prop.id || '').toLowerCase();
  if (MATERIAL_OF[id]) return MATERIAL_OF[id];
  for (const [re, m] of MATERIAL_RULES) if (re.test(id)) return m;
  return 'plastic';
}
// Per-material loudness trims (dB, calibrated with tools/audio_render.mjs so every material
// reads at the same loudness) and reverb sends (resonant materials get more room).
const MAT_TRIM_DB = { soft: 0, squishy: 0.6, crunchy: 2, plastic: 2.4, wood: 0.2, metal: -0.6, ceramic: 1.5, fruit: 1.5, person: 1.3, vehicle: 2.3 };
const MAT_SEND = { soft: 0.05, squishy: 0.05, crunchy: 0.05, plastic: 0.07, wood: 0.1, metal: 0.16, ceramic: 0.15, fruit: 0.06, person: 0.07, vehicle: 0.05 };

// ------------------------------------------------------------------ voice
// One sound event: its parts feed `out`; `out` feeds the SFX bus (and the reverb send).
// The engine tracks voices so it can cap and steal them.
class Voice {
  constructor(au, t, { kind = 'sfx', send = 0, pan = 0, gain = 1 } = {}) {
    const c = au.ctx;
    this.au = au; this.t = t; this.end = t; this.kind = kind; this.last = null;
    this.out = c.createGain();
    this.out.gain.value = gain * dbToGain(FADER_DB[kind] || 0); // the sound's mixer fader
    let node = this.out;
    if (pan && c.createStereoPanner) {
      this.pan = c.createStereoPanner(); this.pan.pan.value = pan;
      this.out.connect(this.pan); node = this.pan;
    }
    node.connect(au.sfxIn);
    if (send > 0) {
      this.send = c.createGain(); this.send.gain.value = send;
      node.connect(this.send); this.send.connect(au.verbIn);
    }
    au._register(this);
  }
  hold(src, stopAt) { if (stopAt >= this.end) { this.end = stopAt; this.last = src; } }
  done() { if (this.last) this.last.onended = () => this.free(); }
  free() {
    if (this.dead) return;
    this.dead = true;
    try { this.out.disconnect(); if (this.pan) this.pan.disconnect(); if (this.send) this.send.disconnect(); } catch (e) { /* already gone */ }
  }
  fadeOut(at, tau = 0.012) {
    const g = this.out.gain;
    g.cancelScheduledValues(at); g.setTargetAtTime(0, at, tau);
    this.end = Math.min(this.end, at + tau * 8);
  }
}

// ------------------------------------------------------------------ synthesis parts
// All parts take (au, v, t, opts) and schedule into voice `v` at audio time `t`.
// Envelopes: linear attack `a`, optional `hold`, exponential decay reaching ~-43 dB at `d`.
function env(g, t, a, hold, d, vol) {
  g.gain.setValueAtTime(0, t);
  g.gain.linearRampToValueAtTime(vol, t + a);
  if (hold) g.gain.setValueAtTime(vol, t + a + hold);
  g.gain.setTargetAtTime(0, t + a + (hold || 0), d / 5);
  return t + a + (hold || 0) + d * 1.4 + 0.02;
}
function filt(au, type, f, q, from) {
  const n = au.ctx.createBiquadFilter();
  n.type = type; n.frequency.value = f; n.Q.value = q;
  from.connect(n);
  return n;
}
function osc(au, v, t, o) {
  const c = au.ctx, n = c.createOscillator(), g = c.createGain();
  n.type = o.type || 'sine';
  const fr = n.frequency;
  if (o.f0) { fr.setValueAtTime(o.f0, t); fr.exponentialRampToValueAtTime(o.f, t + (o.glide || 0.04)); } else fr.setValueAtTime(o.f, t);
  if (o.f1) fr.exponentialRampToValueAtTime(o.f1, t + (o.glide || 0.04) + (o.glide2 || 0.1));
  if (o.vib) { // vibrato / wobble LFO, fading in over vib.fade
    const l = c.createOscillator(), lg = c.createGain();
    l.frequency.value = o.vib.rate;
    lg.gain.setValueAtTime(0, t); lg.gain.linearRampToValueAtTime(o.f * o.vib.depth, t + (o.vib.fade || 0.05));
    l.connect(lg); lg.connect(fr); l.start(t); l.stop(t + (o.a || 0.005) + (o.hold || 0) + (o.d || 0.15) * 1.4 + 0.05);
  }
  n.connect(g);
  const stop = env(g, t, o.a ?? 0.004, o.hold, o.d ?? 0.15, o.vol);
  let tail = g;
  if (o.lp) tail = filt(au, 'lowpass', o.lp, o.lpq ?? 0.7, tail);
  if (o.hp) tail = filt(au, 'highpass', o.hp, 0.7, tail);
  tail.connect(o.to || v.out);
  n.start(t); n.stop(stop); v.hold(n, stop);
  return n;
}
function noise(au, v, t, o) {
  const c = au.ctx, s = c.createBufferSource(), g = c.createGain();
  s.buffer = o.pink ? au.pinkBuf : au.noiseBuf; s.loop = true;
  const f = c.createBiquadFilter();
  f.type = o.type || 'bandpass'; f.Q.value = o.q ?? 1;
  f.frequency.setValueAtTime(o.f, t);
  if (o.f1) f.frequency.exponentialRampToValueAtTime(o.f1, t + (o.sweep || o.d || 0.1));
  s.connect(f); f.connect(g);
  const stop = env(g, t, o.a ?? 0.003, o.hold, o.d ?? 0.08, o.vol);
  let tail = g;
  if (o.lp) tail = filt(au, 'lowpass', o.lp, 0.7, tail);
  tail.connect(o.to || v.out);
  s.start(t, au.rnd(0, 0.9)); s.stop(stop); v.hold(s, stop);
  return s;
}
// FM bell: bright strike that mellows as the modulation index decays.
function bell(au, v, t, o) {
  const c = au.ctx, car = c.createOscillator(), mod = c.createOscillator(), mg = c.createGain(), g = c.createGain();
  const ratio = o.ratio || 2.76, d = o.d ?? 0.6;
  car.frequency.value = o.f; mod.frequency.value = o.f * ratio;
  const dev = (o.index ?? 1.2) * o.f * ratio;
  mg.gain.setValueAtTime(dev, t); mg.gain.setTargetAtTime(0, t, (o.idecay ?? d * 0.3) / 4);
  mod.connect(mg); mg.connect(car.frequency);
  car.connect(g);
  const stop = env(g, t, o.a ?? 0.002, o.hold, d, o.vol);
  filt(au, 'lowpass', o.lp || 7500, 0.7, g).connect(o.to || v.out);
  car.start(t); mod.start(t); car.stop(stop); mod.stop(stop); v.hold(car, stop);
}
// Soft pad tone: detuned pair through a lowpass, slow attack. Used under chords.
function pad(au, v, t, o) {
  for (const det of [-6, 6]) {
    const c = au.ctx, n = c.createOscillator(), g = c.createGain();
    n.type = o.type || 'triangle'; n.frequency.value = o.f; n.detune.value = det;
    if (o.f0) { n.frequency.setValueAtTime(o.f0, t); n.frequency.exponentialRampToValueAtTime(o.f, t + (o.glide || 0.3)); }
    n.connect(g);
    const stop = env(g, t, o.a ?? 0.05, o.hold, o.d ?? 0.8, o.vol / 2);
    const lp = filt(au, 'lowpass', o.lp || 2400, 0.6, g);
    if (o.lp0) { lp.frequency.setValueAtTime(o.lp0, t); lp.frequency.exponentialRampToValueAtTime(o.lp || 2400, t + (o.glide || 0.3)); }
    lp.connect(o.to || v.out);
    n.start(t); n.stop(stop); v.hold(n, stop);
  }
}

// ------------------------------------------------------------------ material recipes
// (au, v, t, f = combo note already shifted for size, w = size weight 0..1, g = peak gain, p = prop)
const RECIPES = {
  // plush / leafy / fabric: a cushioned "pomf" with a breath of fluff
  soft(au, v, t, f, w, g) {
    const d = 0.2 + 0.14 * w;
    osc(au, v, t, { f, f0: f * 1.2, glide: 0.07, a: 0.014, d, vol: g * 0.8 });
    osc(au, v, t, { f: f * 2, f0: f * 2.25, glide: 0.06, a: 0.012, d: d * 0.45, vol: g * 0.12 });
    noise(au, v, t, { type: 'lowpass', f: 1000 - 450 * w, q: 0.5, a: 0.012, d: 0.12 + 0.1 * w, vol: g * 0.4, pink: true });
  },
  // cakes, cream, jelly: an upward "blup" with a little wet squelch and wobble
  squishy(au, v, t, f, w, g) {
    const d = 0.2 + 0.14 * w;
    osc(au, v, t, { f, f0: f * 0.7, glide: 0.05, a: 0.007, d, vol: g * 0.8, vib: { rate: 15, depth: 0.02, fade: 0.1 } });
    osc(au, v, t, { type: 'triangle', f: f * 1.5, f0: f * 1.05, glide: 0.05, a: 0.007, d: d * 0.4, vol: g * 0.1, lp: 3000 });
    noise(au, v, t + 0.005, { type: 'bandpass', f: 1500 - 500 * w, f1: 420, sweep: 0.09, q: 3.5, a: 0.006, d: 0.1, vol: g * 0.32, pink: true });
  },
  // cookies, hard candy, sand: a plucked note under a few soft crumbs (band-limited, low)
  crunchy(au, v, t, f, w, g) {
    osc(au, v, t, { type: 'triangle', f, f0: f * 1.03, glide: 0.02, a: 0.003, d: 0.24 + 0.12 * w, vol: g * 0.75, lp: Math.min(5000, f * 4) });
    osc(au, v, t, { f: f / 2, a: 0.004, d: 0.14, vol: g * 0.22 });
    const n = 3 + Math.round(2 * w + au.rnd(0, 1.4)), lo = 1600 - 600 * w;
    let at = t + 0.004;
    for (let k = 0; k < n; k++) {
      noise(au, v, at, { type: 'bandpass', f: au.rnd(lo, lo * 1.8), q: 1.4, a: 0.002, d: au.rnd(0.014, 0.024), vol: g * au.rnd(0.22, 0.34) * (1 - k * 0.1), lp: 5200 });
      at += au.rnd(0.014, 0.026) * (1 + w);
    }
  },
  // toys: a hollow "plok" (triangle + a short ringing body resonance). The duck squeaks.
  plastic(au, v, t, f, w, g, p) {
    if (p.id === 'duck') {
      osc(au, v, t, { type: 'triangle', f: f * 1.9, f0: f * 1.45, glide: 0.05, f1: f * 1.6, glide2: 0.08, a: 0.01, d: 0.15, vol: g * 0.45, lp: 2600, lpq: 2, vib: { rate: 24, depth: 0.03, fade: 0.03 } });
      g *= 0.6;
    }
    osc(au, v, t, { type: 'triangle', f, f0: f * 1.09, glide: 0.025, a: 0.003, d: 0.24 + 0.12 * w, vol: g * 0.75 });
    osc(au, v, t, { f: f * 2, a: 0.003, d: 0.1, vol: g * 0.16 });
    noise(au, v, t, { type: 'bandpass', f: Math.min(4200, f * 2.4), q: 9, a: 0.002, d: 0.05, vol: g * 0.45 });
  },
  // wood: a marimba-like "tonk": fundamental + tuned 4th partial + a dry knock
  wood(au, v, t, f, w, g) {
    const d = 0.22 + 0.22 * w;
    osc(au, v, t, { f, a: 0.002, d, vol: g * 0.8 });
    osc(au, v, t, { f: f * 4, a: 0.0015, d: 0.04, vol: g * (f * 4 < 5000 ? 0.15 : 0.04) });
    noise(au, v, t, { type: 'bandpass', f: 1100 - 450 * w, q: 1.3, a: 0.0015, d: 0.022, vol: g * 0.22 });
    if (w > 0.35) osc(au, v, t, { f: f / 2, a: 0.004, d: d * 1.2, vol: g * 0.3 });
  },
  // metal: an FM "ting" (small) or a softer "bong" (big)
  metal(au, v, t, f, w, g) {
    const big = w > 0.42, fc = big ? f : fold(f * 2, 2600);
    bell(au, v, t, { f: fc, ratio: big ? 1.41 : 2.76, index: big ? 1.1 : 0.9, a: 0.002, d: 0.45 + 0.5 * w, vol: g * 0.5, lp: 6500 });
    osc(au, v, t, { f: fc * 0.5, a: 0.003, d: 0.12 + 0.2 * w, vol: g * 0.28 });
    noise(au, v, t, { type: 'bandpass', f: 2600, q: 2, a: 0.001, d: 0.012, vol: g * 0.1 });
    if (big) osc(au, v, t, { f: f / 2, a: 0.006, d: 0.5, vol: g * 0.3 });
  },
  // china and glass: a clean "clink" (two inharmonic partials), delicate
  ceramic(au, v, t, f, w, g) {
    const fc = w > 0.35 ? f : fold(f * 2, 3200);
    osc(au, v, t, { f: fc, a: 0.0015, d: 0.3 + 0.25 * w, vol: g * 0.5 });
    osc(au, v, t, { f: fc * 2.32, a: 0.0012, d: 0.12, vol: g * (fc * 2.32 < 6000 ? 0.16 : 0.05) });
    noise(au, v, t, { type: 'bandpass', f: 3000, q: 2.5, a: 0.001, d: 0.01, vol: g * 0.08 });
    if (w > 0.35) osc(au, v, t, { f: f / 2, a: 0.004, d: 0.25, vol: g * 0.28 });
  },
  // fruit: a juicy water-drop "plip" (up-chirp) over a soft pluck
  fruit(au, v, t, f, w, g) {
    osc(au, v, t, { f: f * 1.2, f0: f * 0.55, glide: 0.035, a: 0.004, d: 0.16 + 0.08 * w, vol: g * 0.72 });
    osc(au, v, t, { type: 'triangle', f, a: 0.005, d: 0.22 + 0.1 * w, vol: g * 0.35, lp: 2500 });
    noise(au, v, t + 0.012, { type: 'bandpass', f: 2000, f1: 850, sweep: 0.05, q: 2.5, a: 0.003, d: 0.05, vol: g * 0.22, pink: true });
  },
  // people and critters: a cute tiny "boop" (soft falling blip). Never a scream.
  person(au, v, t, f, w, g, p) {
    const fb = clamp(f, 520, 1400);
    const blip = (at, k) => {
      osc(au, v, at, { f: fb * 0.94 * k, f0: fb * 1.12 * k, glide: 0.08, a: 0.012, d: 0.15, vol: g * 0.6 });
      osc(au, v, at, { type: 'triangle', f: fb * 0.94 * k, f0: fb * 1.12 * k, glide: 0.08, a: 0.012, d: 0.1, vol: g * 0.14, lp: 1300, lpq: 1.5 });
    };
    blip(t, 1);
    if (p.id === 'crab') blip(t + 0.07, 1.12);
  },
  // cars, buses, bikes: a little "vroom-down" plus a polite in-key "meep" (rate-limited)
  vehicle(au, v, t, f, w, g, p) {
    if (p.id === 'bike') { // bicycle bell, two dings
      bell(au, v, t, { f: au.deg(2, 1), ratio: 3.2, index: 0.7, d: 0.35, vol: g * 0.4 });
      bell(au, v, t + 0.09, { f: au.deg(2, 1), ratio: 3.2, index: 0.7, d: 0.45, vol: g * 0.36 });
      return;
    }
    const big = w > 0.5, fe = clamp(f / (big ? 8 : 4), 55, 160);
    osc(au, v, t, { type: 'sawtooth', f: fe * 0.7, f0: fe * 1.35, glide: 0.25, a: 0.015, d: 0.3 + 0.2 * w, vol: g * 0.5, lp: 650, lpq: 1.4 });
    osc(au, v, t, { type: 'triangle', f: fe * 1.4, f0: fe * 2.7, glide: 0.25, a: 0.015, d: 0.25, vol: g * 0.2, lp: 900 });
    noise(au, v, t, { type: 'lowpass', f: 420, q: 0.8, a: 0.005, d: 0.09, vol: g * 0.4, pink: true });
    if (t - au.lastHorn > 0.8) {
      au.lastHorn = t;
      const hd = big ? 0.15 : 0.07, oct = big ? -1 : 0;
      const beeps = big ? 1 : 2;
      for (let b = 0; b < beeps; b++) for (const n of [0, 2]) {
        osc(au, v, t + 0.04 + b * (hd + 0.06), { type: 'square', f: au.deg(n, oct), a: 0.008, hold: hd, d: 0.05, vol: g * 0.07, lp: 1500, lpq: 0.9 });
      }
    }
  },
};

// ------------------------------------------------------------------ engine
export class Audio {
  constructor() {
    this.ctx = null; this.sfxOn = true; this.musicOn = true;
    this.sfxVol = 1; this.musicVol = 1;
    this.want = null; this.wantId = null; this.track = null;
    this.musicBase = 'music/'; this.urls = {};
    this.bytes = {}; this.decoded = new Map(); this.loading = {}; this.failed = {};
    this.stopped = {};           // id -> { pos, at } for resume
    this.buffers = {};           // legacy load(name, url) results
    this.voices = [];
    this.popClock = 0; this.popTimes = []; this.popN = 0;
    this.lastGulp = -1; this.lastHorn = -1; this.lastWobble = -9; this.wobbles = [];
    this.duckEnd = 0; this.duckDepth = 1;
    this.lastReward = -9; this.lastDing = -9;
    this.rng = Math.random;
    this._setKey(MUSIC.peaceful_village.root, MUSIC.peaceful_village.cents);
  }

  // ---------------------------------------------------------------- context + graph
  // Must be called from a user gesture (iOS). Safe to call on every tap.
  unlock() {
    if (!this.ctx) {
      const C = window.AudioContext || window.webkitAudioContext;
      if (!C) return;
      let ctx;
      try { ctx = new C({ latencyHint: 'interactive' }); } catch (e) { ctx = new C(); }
      this.attach(ctx);
      document.addEventListener('visibilitychange', () => {
        if (!this.ctx) return;
        if (document.hidden) { if (this.ctx.state === 'running') this.ctx.suspend().catch(() => {}); } else this.ctx.resume().catch(() => {});
      });
    }
    const c = this.ctx;
    if (c.state !== 'running') c.resume().catch(() => {});
    if (!this.kicked) { // iOS: actually start a (silent) source inside the gesture
      const b = c.createBuffer(1, 1, c.sampleRate), s = c.createBufferSource();
      s.buffer = b; s.connect(c.destination); s.start(0);
      this.kicked = true;
    }
    if (this.wantId && this.musicOn && (!this.track || this.track.id !== this.wantId)) this.playMusic(this.want);
  }
  // Build the mix graph on any BaseAudioContext (an OfflineAudioContext in the tests).
  // opts.noLimiter (tests only) bypasses the safety limiter to measure raw peaks.
  attach(ctx, opts = {}) {
    this.ctx = ctx;
    this.offline = typeof OfflineAudioContext !== 'undefined' && ctx instanceof OfflineAudioContext;
    const c = ctx;
    // clocks are in this context's time
    this.voices = []; this.popClock = 0; this.popTimes = []; this.track = null;
    this.lastGulp = -1; this.lastHorn = -1; this.lastWobble = -9; this.wobbles = []; this.duckEnd = 0; this.duckDepth = 1;
    this.lastReward = -9; this.lastDing = -9;
    // master: limiter (safety) + makeup compensation, so unity in = unity out below threshold
    this.master = c.createGain();
    this.limiter = comp(c, LIMIT);
    this.limTrim = c.createGain(); this.limTrim.gain.value = 1 / makeupGain(LIMIT);
    if (opts.noLimiter) this.master.connect(c.destination);
    else { this.master.connect(this.limiter); this.limiter.connect(this.limTrim); this.limTrim.connect(c.destination); }
    // sfx: bus -> glue -> makeup compensation -> master
    this.sfxIn = c.createGain();
    this.sfxBus = c.createGain(); this.sfxBus.gain.value = this.sfxOn ? dbToGain(SFX_DB) * this.sfxVol : 0;
    this.glue = comp(c, GLUE);
    this.glueTrim = c.createGain(); this.glueTrim.gain.value = 1 / makeupGain(GLUE);
    this.sfxIn.connect(this.sfxBus); this.sfxBus.connect(this.glue); this.glue.connect(this.glueTrim); this.glueTrim.connect(this.master);
    // reverb send: small bright room, kept out of the lows
    this.verbIn = c.createGain(); this.verbIn.gain.value = this.sfxOn ? 1 : 0;
    this.verb = c.createConvolver(); this.verb.normalize = false; this.verb.buffer = roomIR(c, this.rng);
    const vh = c.createBiquadFilter(); vh.type = 'highpass'; vh.frequency.value = 280; vh.Q.value = 0.6;
    const vl = c.createBiquadFilter(); vl.type = 'lowpass'; vl.frequency.value = 6500; vl.Q.value = 0.6;
    this.verbIn.connect(this.verb); this.verb.connect(vh); vh.connect(vl); vl.connect(this.master);
    // music: per-track fades -> bus (on/off, level) -> duck -> master
    this.musicBus = c.createGain(); this.musicBus.gain.value = this.musicOn ? dbToGain(MUSIC_DB) * this.musicVol : 0;
    this.duckG = c.createGain();
    this.musicBus.connect(this.duckG); this.duckG.connect(this.master);
    // shared noise sources
    this.noiseBuf = noiseBuffer(c, false, this.rng); this.pinkBuf = noiseBuffer(c, true, this.rng);
    // legacy aliases (old code exposed these names)
    this.sfx = this.sfxBus; this.music = this.musicBus; this.comp = this.glue;
  }
  _live() {
    const c = this.ctx;
    return !!c && this.sfxOn && (this.offline || c.state === 'running');
  }
  rnd(a, b) { return a + (b - a) * this.rng(); }

  // ---------------------------------------------------------------- settings
  setSfx(on) {
    this.sfxOn = !!on;
    if (!this.ctx) return;
    const t = this.ctx.currentTime, v = on ? dbToGain(SFX_DB) * this.sfxVol : 0;
    this.sfxBus.gain.setTargetAtTime(v, t, 0.02);
    this.verbIn.gain.setTargetAtTime(on ? 1 : 0, t, 0.02);
  }
  setMusic(on) {
    this.musicOn = !!on;
    if (!this.ctx) return;
    const t = this.ctx.currentTime;
    this.musicBus.gain.setTargetAtTime(on ? dbToGain(MUSIC_DB) * this.musicVol : 0, t, 0.12);
    if (!on) this._stopTrack(0.6);
    else if (this.want) this.playMusic(this.want);
  }
  setSfxVolume(v) { this.sfxVol = clamp(v, 0, 1); this.setSfx(this.sfxOn); }
  setMusicVolume(v) {
    this.musicVol = clamp(v, 0, 1);
    if (this.ctx && this.musicOn) this.musicBus.gain.setTargetAtTime(dbToGain(MUSIC_DB) * this.musicVol, this.ctx.currentTime, 0.1);
  }

  // ---------------------------------------------------------------- key (SFX follow the music)
  _setKey(root, cents) {
    this.root = root; this.cents = cents || 0;
    this.rootMidi = root <= 5 ? 72 + root : 60 + root; // home octave F#4..F5
    this.comboScale = [];
    for (let m = COMBO_LO; m <= COMBO_HI; m++) if (PENTA.includes((((m - root) % 12) + 12) % 12)) this.comboScale.push(m);
  }
  midiHz(m) { return 440 * Math.pow(2, (m - 69 + this.cents / 100) / 12); }
  // Pentatonic degree n (0 = root, 5 = root an octave up; negatives go down), in octave `oct`.
  deg(n, oct = 0) {
    const o = Math.floor(n / 5), d = PENTA[((n % 5) + 5) % 5];
    return this.midiHz(this.rootMidi + 12 * (o + oct) + d);
  }
  // Combo melody: climbs the scale, then keeps sparkling up the top five notes.
  comboHz(combo) {
    const s = this.comboScale, N = s.length;
    const c = Math.max(1, combo | 0);
    const i = c <= N ? c - 1 : N - 5 + ((c - N - 1) % 5);
    return this.midiHz(s[i]);
  }
  keyOf(key) { const id = this._trackId(key); return id ? { root: MUSIC[id].root, cents: MUSIC[id].cents } : null; }

  // ---------------------------------------------------------------- music
  _trackId(key) {
    if (!key) return null;
    if (MUSIC[key]) return key;
    return MUSIC_KEYS[key] || null;
  }
  setMusicBase(base) { this.musicBase = base.endsWith('/') ? base : base + '/'; }
  // Point a track at another URL (for example a data: URL in a single-file build).
  setTrackUrl(id, url) { this.urls[this._trackId(id) || id] = url; }
  _url(id) { return this.urls[id] || this.musicBase + id + '.m4a'; }

  async _bytes(id) {
    if (this.bytes[id]) return this.bytes[id];
    const url = this._url(id);
    let ab;
    if (url.startsWith('data:')) { // some sandboxes block fetch() of data: URLs
      const bin = atob(url.slice(url.indexOf(',') + 1));
      const u8 = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i);
      ab = u8.buffer;
    } else {
      const r = await fetch(url);
      if (!r.ok) throw new Error(`HTTP ${r.status} for ${url}`);
      ab = await r.arrayBuffer();
    }
    this.bytes[id] = ab;
    return ab;
  }
  _decode(ab) {
    // Callback form works on old Safari too; decodeAudioData detaches its input, so copy.
    return new Promise((res, rej) => {
      const p = this.ctx.decodeAudioData(ab.slice(0), res, rej);
      if (p && p.catch) p.catch(rej);
    });
  }
  async _loadTrack(id) {
    if (this.decoded.has(id)) { const b = this.decoded.get(id); this.decoded.delete(id); this.decoded.set(id, b); return b; }
    if (this.loading[id]) return this.loading[id];
    if (this.failed[id] && performance.now() - this.failed[id] < 10000) return null;
    this.loading[id] = (async () => {
      try {
        const buf = await this._decode(await this._bytes(id));
        this.decoded.set(id, buf);
        this._trimCache();
        return buf;
      } catch (e) {
        this.failed[id] = performance.now();
        console.warn('music load failed', id, e);
        return null;
      } finally { delete this.loading[id]; }
    })();
    return this.loading[id];
  }
  _trimCache() {
    const playing = this.track && this.track.id;
    for (const id of [...this.decoded.keys()]) {
      if (this.decoded.size <= DECODED_CACHE) break;
      if (id !== playing && id !== this.wantId) this.decoded.delete(id);
    }
  }
  // Fetch (not decode) a track ahead of time, e.g. while the level map is up.
  preload(key) { const id = this._trackId(key); if (id) this._bytes(id).catch(() => {}); }

  playMusic(key, opts = {}) {
    if (opts === true) opts = { force: true }; // old signature playMusic(name, force)
    const id = this._trackId(key);
    if (!id) {
      if (this.buffers[key]) return this._playLegacy(key, opts); // legacy load(name, url)
      console.warn('unknown music key', key);
      return;
    }
    this.want = key; this.wantId = id;
    this._setKey(MUSIC[id].root, MUSIC[id].cents);
    if (!this.ctx || !this.musicOn) return;
    if (this.track && this.track.id === id && !opts.force) return;
    this._loadTrack(id).then((buf) => {
      if (!buf || this.wantId !== id || !this.musicOn) return;
      if (this.track && this.track.id === id && !opts.force) return;
      this._startTrack(id, buf, opts);
    });
  }
  _startTrack(id, buf, opts = {}) {
    const c = this.ctx, now = c.currentTime;
    const src = c.createBufferSource();
    src.buffer = buf; src.loop = true;
    const known = id in MUSIC, pad = known ? MUSIC_PAD : 0;
    const len = known ? Math.min(MUSIC[id].len, buf.duration - 2 * pad) : buf.duration;
    src.loopStart = pad; src.loopEnd = pad + len;
    const g = c.createGain(); g.gain.value = 0;
    src.connect(g); g.connect(this.musicBus);
    let off = 0;
    const st = this.stopped[id];
    if (st && !opts.restart && now - st.at < RESUME_WITHIN) off = st.pos;
    src.start(now, pad + off);
    const level = dbToGain(TRACK_TRIM_DB[id] || 0);
    const fade = this.track ? XFADE : Math.min(XFADE, 0.9);
    const fd = { t0: now, dur: fade, from: 0, to: level, fadeIn: true };
    rampCurve(g.gain, fd);
    this._stopTrack(fade);
    this.track = { id, src, g, startAt: now, off, len, fd };
  }
  _stopTrack(fade = 0.8) {
    const t = this.track;
    if (!t) return;
    this.track = null;
    const c = this.ctx, now = c.currentTime;
    if (t.len) this.stopped[t.id] = { pos: (t.off + now - t.startAt) % t.len, at: now };
    // Start the fade-out from the exact value our own fade-in curve has reached (computed,
    // not read back: Firefox does not report automated AudioParam values).
    rampCurve(t.g.gain, { t0: now, dur: fade, from: curveValue(t.fd, now), to: 0, fadeIn: false });
    try { t.src.stop(now + fade + 0.05); } catch (e) { /* already stopped */ }
    t.src.onended = () => { try { t.g.disconnect(); } catch (e) { /* gone */ } };
  }
  stopMusic() { this.want = null; this.wantId = null; this._stopTrack(0.8); }
  // Legacy: load(name, url) then playMusic(name) plays any buffer as a plain loop.
  async load(name, url) {
    if (!this.ctx) return;
    try {
      this.urls[name] = url;
      const buf = await this._decode(await this._bytes(name));
      this.buffers[name] = buf;
      if (this.want === name) this._playLegacy(name, { force: true });
    } catch (e) { console.warn('music load failed', name, e); }
  }
  _playLegacy(name, opts) {
    this.want = name; this.wantId = null;
    if (!this.ctx || !this.musicOn) return;
    if (this.track && this.track.id === name && !opts.force) return;
    this._startTrack(name, this.buffers[name], opts);
  }

  // Dip the music under a moment (sidechain style). Overlapping ducks keep the deepest.
  // Only setTargetAtTime events are used, so every new duck glides on from the true
  // current gain (no reads of AudioParam.value, no jumps).
  duck(db, hold = 0.2, release = 0.5) {
    if (!this.ctx) return;
    const p = this.duckG.gain, now = this.ctx.currentTime;
    let target = dbToGain(db);
    if (now < this.duckEnd) target = Math.min(target, this.duckDepth);
    this.duckDepth = target;
    this.duckEnd = Math.max(now + 0.03 + hold, this.duckEnd);
    p.cancelScheduledValues(now);
    p.setTargetAtTime(target, now, 0.015);
    p.setTargetAtTime(1, this.duckEnd, release / 4);
  }

  // ---------------------------------------------------------------- voices
  _register(v) {
    const now = this.ctx.currentTime;
    this.voices = this.voices.filter((x) => !x.dead && x.end > now);
    if (v.kind === 'pop') {
      const pops = this.voices.filter((x) => x.kind === 'pop');
      if (pops.length >= POP_VOICES) pops[0].fadeOut(Math.max(now, v.t - 0.01));
    }
    this.voices.push(v);
  }

  // ---------------------------------------------------------------- swallow sounds
  // prop: { id, value } (a bare number still works: the old pop(value, combo)).
  pop(prop, combo = 1) {
    if (!this._live()) return;
    const p = typeof prop === 'number' ? { value: prop } : (prop || {});
    const value = Math.max(1, +p.value || 1);
    const mat = materialOf(p);
    const now = this.ctx.currentTime;
    const t = Math.max(now + 0.004, this.popClock + POP_STRUM);
    if (t - now > POP_BACKLOG) return; // a big pile: the run already says "lots"
    this.popClock = t;
    this.popTimes = this.popTimes.filter((x) => x > now - 0.35);
    this.popTimes.push(t);
    const dens = this.popTimes.length;
    const w = clamp(Math.log(value) / Math.log(200), 0, 1);
    const oct = value >= 40 ? -2 : value >= 4 ? -1 : 0;
    const f = this.comboHz(combo) * Math.pow(2, oct) * Math.pow(2, this.rnd(-6, 6) / 1200);
    let g = POP_GAIN * dbToGain(MAT_TRIM_DB[mat] + this.rnd(-1, 1));
    g *= clamp(Math.pow(f / 700, -0.3), 0.7, 1.35);          // equal-loudness: highs sound louder
    g *= dbToGain(4 * Math.min(w, 0.5));                      // bigger things land a little heavier
    if (dens > 3) g /= Math.sqrt(1 + 0.35 * (dens - 3));     // anti machine-gun
    const pan = (this.popN++ % 2 ? 1 : -1) * this.rnd(0.05, 0.16);
    const v = new Voice(this, t, { kind: 'pop', send: MAT_SEND[mat], pan });
    RECIPES[mat](this, v, t, f, w, g, p);
    v.done();
    if (value >= 15) this._gulpAt(t, value);
    else if (value >= 4) this._thump(t, value);
    if (combo >= 10 && combo % 10 === 0) this._sparkle(t + 0.05, Math.min(1, combo / 40));
    if (dens >= 5) this.duck(-1.5, 0.15, 0.4);
  }
  // The deep satisfying swallow under big things. Rate-limited so a stack can't boom.
  gulp(value = 30) { if (this._live()) this._gulpAt(this.ctx.currentTime + 0.004, value); }
  _gulpAt(t, value) {
    if (t - this.lastGulp < 0.14) return;
    this.lastGulp = t;
    const k = clamp((value - 10) / 150, 0, 1);
    const v = new Voice(this, t, { kind: 'gulp', send: 0.06 });
    const g = 0.42 + 0.1 * k;
    const f0 = 230 - 60 * k, f1 = 72 - 18 * k, dt = 0.16 + 0.08 * k;
    osc(this, v, t, { f: f1, f0, glide: dt, a: 0.008, hold: 0.04, d: 0.28 + 0.2 * k, vol: g });
    // harmonics so the gulp still reads on a phone speaker (which cannot play 70 Hz)
    osc(this, v, t, { type: 'triangle', f: f1 * 2, f0: f0 * 2, glide: dt, a: 0.008, d: 0.22 + 0.1 * k, vol: g * 0.32, lp: 900 });
    noise(this, v, t + 0.06, { type: 'lowpass', f: 380, q: 0.7, a: 0.02, d: 0.14 + 0.08 * k, vol: g * 0.35, pink: true });
    if (k > 0.25) osc(this, v, t + 0.2 + 0.05 * k, { f: 520, f0: 300, glide: 0.06, a: 0.006, d: 0.08, vol: 0.06 }); // swallow bubble
    v.done();
    this.duck(-2.5, 0.2, 0.45);
  }
  _thump(t, value) {
    const k = clamp((value - 4) / 11, 0, 1);
    const v = new Voice(this, t, { kind: 'thump' });
    osc(this, v, t, { f: 95 - 20 * k, f0: 170 - 30 * k, glide: 0.07, a: 0.006, d: 0.16 + 0.06 * k, vol: 0.2 + 0.08 * k });
    osc(this, v, t, { type: 'triangle', f: 190 - 40 * k, f0: 340 - 60 * k, glide: 0.07, a: 0.006, d: 0.1, vol: 0.06, lp: 800 });
    v.done();
  }
  _sparkle(t, k) {
    const v = new Voice(this, t, { kind: 'sparkle', send: 0.25 });
    [3, 5, 7].forEach((n, j) => bell(this, v, t + j * 0.05, { f: fold(this.deg(n, 1), 2400), ratio: 3.5, index: 0.5, d: 0.4, vol: 0.05 + 0.03 * k }));
    v.done();
  }

  // ---------------------------------------------------------------- game sounds
  sizeUp() { // grew a size: a bright run up and a bloom
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'sizeUp', send: 0.14 });
    [0, 1, 2, 3, 5].forEach((n, j) => {
      osc(this, v, t + j * 0.055, { type: 'triangle', f: this.deg(n), a: 0.006, d: 0.28, vol: 0.13, lp: 4000 });
      osc(this, v, t + j * 0.055, { f: this.deg(n, 1), a: 0.004, d: 0.12, vol: 0.03 });
    });
    pad(this, v, t + 0.27, { f: this.deg(5), a: 0.04, d: 0.7, vol: 0.09, lp: 3000 });
    pad(this, v, t + 0.27, { f: this.deg(7), a: 0.04, d: 0.7, vol: 0.07, lp: 3000 });
    bell(this, v, t + 0.27, { f: this.deg(7), ratio: 3.5, index: 0.5, d: 0.6, vol: 0.05 });
    noise(this, v, t, { type: 'bandpass', f: 500, f1: 3000, sweep: 0.3, q: 1.2, a: 0.12, d: 0.2, vol: 0.025, pink: true });
    v.done();
    this.duck(-3, 0.3, 0.5);
  }
  target(progress = 0) { // a target item eaten: an in-key chime that climbs with progress
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.012, v = new Voice(this, t, { kind: 'target', send: 0.22 });
    const n = 2 + Math.round(clamp(progress, 0, 1) * 3); // mi, sol, la ... the last one resolves to do
    bell(this, v, t, { f: this.deg(n), ratio: 3.5, index: 0.8, d: 0.7, vol: 0.13 });
    osc(this, v, t, { f: this.deg(n), a: 0.004, d: 0.5, vol: 0.06 });
    osc(this, v, t + 0.06, { f: fold(this.deg(n, 1), 2400), a: 0.004, d: 0.35, vol: 0.025 });
    v.done();
  }
  // Too big to swallow: a soft rubbery "uh-uh". Rate-limited, and it backs off if you
  // keep nudging the same big thing.
  rimWobble() {
    if (!this._live()) return;
    const now = this.ctx.currentTime;
    this.wobbles = this.wobbles.filter((x) => x > now - 6);
    const gap = this.wobbles.length >= 3 ? 2.5 : 0.9;
    if (now - this.lastWobble < gap) return;
    this.lastWobble = now; this.wobbles.push(now);
    const t = now + 0.005, v = new Voice(this, t, { kind: 'rimWobble', send: 0.04 });
    [[1, 0], [0, 0.13]].forEach(([n, at]) => {
      osc(this, v, t + at, { type: 'triangle', f: this.deg(n, -1), f0: this.deg(n, -1) * 1.06, glide: 0.05, a: 0.012, d: 0.12, vol: 0.12, lp: 1300, vib: { rate: 13, depth: 0.03, fade: 0.04 } });
    });
    v.done();
  }
  bonk() { this.rimWobble(); } // legacy name
  tick(urgent) { // countdown: a soft wood-block tock (never a click)
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.003, v = new Voice(this, t, { kind: 'tick', send: 0.05 });
    const k = urgent ? 1.35 : 1;
    osc(this, v, t, { f: this.deg(3), a: 0.003, d: 0.1, vol: 0.13 * k });
    osc(this, v, t, { f: fold(this.deg(3, 1), 1800), a: 0.0025, d: 0.04, vol: 0.05 * k });
    noise(this, v, t, { type: 'bandpass', f: 1200, q: 1.6, a: 0.002, d: 0.02, vol: 0.05 * k });
    if (urgent) osc(this, v, t, { f: this.deg(3, -1), a: 0.004, d: 0.12, vol: 0.1 });
    v.done();
  }
  tap() { // UI button
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.003, v = new Voice(this, t, { kind: 'tap' });
    osc(this, v, t, { f: this.deg(5), f0: this.deg(5) * 1.25, glide: 0.02, a: 0.003, d: 0.09, vol: 0.12 });
    osc(this, v, t, { f: this.deg(0), a: 0.003, d: 0.07, vol: 0.06 });
    v.done();
  }
  uiOpen() { // a panel slides in
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.003, v = new Voice(this, t, { kind: 'uiOpen', send: 0.08 });
    osc(this, v, t, { f: this.deg(3), f0: this.deg(0), glide: 0.07, a: 0.01, d: 0.14, vol: 0.06 });
    noise(this, v, t, { type: 'bandpass', f: 900, f1: 2400, sweep: 0.08, q: 0.9, a: 0.03, d: 0.08, vol: 0.012, pink: true });
    v.done();
  }
  uiClose() {
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.003, v = new Voice(this, t, { kind: 'uiClose', send: 0.06 });
    osc(this, v, t, { f: this.deg(0), f0: this.deg(3), glide: 0.07, a: 0.01, d: 0.12, vol: 0.055 });
    noise(this, v, t, { type: 'bandpass', f: 2200, f1: 800, sweep: 0.08, q: 0.9, a: 0.03, d: 0.07, vol: 0.01, pink: true });
    v.done();
  }
  star(i = 0) { // results screen, one per star (called 330 ms apart)
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'star', send: 0.25 });
    const n = [2, 3, 5][clamp(i | 0, 0, 2)];
    bell(this, v, t, { f: fold(this.deg(n, 1), 2200), ratio: 4, index: 0.6, d: 0.9, vol: 0.12 });
    osc(this, v, t, { type: 'triangle', f: this.deg(n), a: 0.004, d: 0.5, vol: 0.07, lp: 3000 });
    if (i >= 2) this._sparkle(t + 0.08, 1);
    v.done();
  }
  win() { // level complete: run up, a warm chord, sparkles
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'win', send: 0.2 });
    for (let j = 0; j < 8; j++) {
      osc(this, v, t + j * 0.055, { type: 'triangle', f: this.deg(j), a: 0.005, d: 0.3, vol: 0.1, lp: 4200 });
      osc(this, v, t + j * 0.055, { f: fold(this.deg(j, 1), 2600), a: 0.004, d: 0.14, vol: 0.025 });
    }
    const c0 = t + 0.47;
    for (const n of [0, 2, 3, 5]) pad(this, v, c0, { f: this.deg(n), a: 0.03, hold: 0.25, d: 1.2, vol: 0.075, lp: 3200 });
    for (const n of [5, 7]) bell(this, v, c0, { f: this.deg(n), ratio: 3.5, index: 0.6, d: 1.1, vol: 0.06 });
    osc(this, v, c0, { type: 'triangle', f: this.deg(0, -2), a: 0.01, d: 0.9, vol: 0.14, lp: 600 });
    for (let k = 0; k < 7; k++) osc(this, v, c0 + 0.08 + k * 0.075, { f: fold(this.deg(Math.floor(this.rnd(5, 12))), 2600), a: 0.003, d: 0.16, vol: 0.022 });
    v.done();
    this.duck(-8, 1.4, 0.8);
  }
  timeUp() { // out of time: a gentle "aww", not a buzzer
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'timeUp', send: 0.15 });
    [4, 3, 2, 0].forEach((n, j) => osc(this, v, t + j * 0.13, { type: 'triangle', f: this.deg(n), a: 0.01, d: j === 3 ? 0.7 : 0.3, vol: 0.11, lp: 2500, vib: j === 3 ? { rate: 5.5, depth: 0.012, fade: 0.3 } : null }));
    osc(this, v, t + 0.39, { f: this.deg(0, -1), a: 0.02, d: 0.8, vol: 0.1 });
    v.done();
    this.duck(-6, 0.8, 0.8);
  }
  swallowedHole() { // a hole eats a hole: a big cartoon GLOMP with a slide down
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005;
    this.lastGulp = -1;
    this._gulpAt(t, 160);
    const v = new Voice(this, t, { kind: 'swallowedHole', send: 0.1 });
    osc(this, v, t + 0.05, { f: this.deg(0, -1), f0: this.deg(0, 1), glide: 0.5, a: 0.03, d: 0.35, vol: 0.06, vib: { rate: 6, depth: 0.03, fade: 0.2 }, lp: 2500 });
    v.done();
    this.duck(-6, 0.6, 0.6);
  }
  levelStart() { // "go!": a short, bright pickup into a chord
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'levelStart', send: 0.18 });
    [[3, -1, 0], [5, -1, 0.09]].forEach(([n, o, at]) => osc(this, v, t + at, { type: 'triangle', f: this.deg(n, o), a: 0.005, d: 0.2, vol: 0.1, lp: 3500 }));
    const c0 = t + 0.18;
    for (const n of [0, 2, 3]) {
      bell(this, v, c0, { f: this.deg(n), ratio: 3.5, index: 0.7, d: 0.6, vol: 0.06 });
      pad(this, v, c0, { f: this.deg(n), a: 0.012, d: 0.6, vol: 0.06, lp: 3500 });
    }
    osc(this, v, c0, { type: 'triangle', f: this.deg(0, -2), a: 0.008, d: 0.5, vol: 0.12, lp: 700 });
    noise(this, v, t, { type: 'bandpass', f: 600, f1: 3500, sweep: 0.18, q: 1.1, a: 0.1, d: 0.15, vol: 0.02, pink: true });
    v.done();
    this.duck(-5, 0.5, 0.6);
  }
  lastOne() { // one target left: an expectant twinkle
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'lastOne', send: 0.25 });
    [3, 4, 5].forEach((n, j) => bell(this, v, t + j * 0.07, { f: fold(this.deg(n, 1), 2200), ratio: 3.5, index: 0.6, d: 0.35, vol: 0.07 }));
    osc(this, v, t + 0.21, { f: fold(this.deg(7, 1), 2400), a: 0.03, hold: 0.25, d: 0.5, vol: 0.045, vib: { rate: 7, depth: 0.006, fade: 0.1 } });
    v.done();
    this.duck(-3, 0.5, 0.5);
  }
  boosterMagnet() { // a whooshy magnetic hum
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'boosterMagnet', send: 0.08 });
    const c = this.ctx, hum = c.createGain();
    const am = c.createOscillator(), amg = c.createGain();
    am.frequency.value = 7; amg.gain.value = 0.35; hum.gain.value = 0.65;
    am.connect(amg); amg.connect(hum.gain); hum.connect(v.out);
    am.start(t); am.stop(t + 1.3);
    osc(this, v, t, { f: this.deg(0, -2), a: 0.15, hold: 0.45, d: 0.45, vol: 0.16, to: hum });
    osc(this, v, t, { f: this.deg(0, -1) * 1.004, a: 0.15, hold: 0.45, d: 0.45, vol: 0.07, to: hum });
    osc(this, v, t, { type: 'triangle', f: this.deg(3, -1), a: 0.15, hold: 0.45, d: 0.45, vol: 0.04, lp: 900, to: hum });
    noise(this, v, t, { type: 'bandpass', f: 400, f1: 2400, sweep: 0.55, q: 1.3, a: 0.25, hold: 0.1, d: 0.5, vol: 0.06, pink: true });
    osc(this, v, t + 0.05, { f: this.deg(5), f0: this.deg(0), glide: 0.45, a: 0.1, d: 0.35, vol: 0.025 });
    v.done();
    this.duck(-3, 0.6, 0.5);
  }
  boosterFreeze() { // an icy chime with a breath of frost
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'boosterFreeze', send: 0.35 });
    [7, 9, 11].forEach((n, j) => bell(this, v, t + j * 0.045, { f: fold(this.deg(n), 2400), ratio: 3.51, index: 0.9, d: 1.1, vol: 0.06 }));
    for (let k = 0; k < 6; k++) osc(this, v, t + 0.12 + k * 0.07, { f: fold(this.deg(Math.floor(this.rnd(10, 15))), 3000), a: 0.002, d: 0.12, vol: 0.02 });
    noise(this, v, t, { type: 'highpass', f: 5000, q: 0.5, a: 0.25, d: 0.6, vol: 0.02, lp: 9000 });
    v.done();
    this.duck(-3, 0.5, 0.6);
  }
  boosterGrow() { // a rising swell that blooms
    if (!this._live()) return;
    const t = this.ctx.currentTime + 0.005, v = new Voice(this, t, { kind: 'boosterGrow', send: 0.15 });
    for (const n of [0, 3, 5]) pad(this, v, t, { type: 'sawtooth', f: this.deg(n, -1), f0: this.deg(n, -2), glide: 0.7, a: 0.5, hold: 0.2, d: 0.5, vol: 0.06, lp: 3500, lp0: 350 });
    noise(this, v, t, { type: 'bandpass', f: 300, f1: 3000, sweep: 0.7, q: 1.4, a: 0.6, d: 0.2, vol: 0.035, pink: true });
    [0, 2, 3].forEach((n) => bell(this, v, t + 0.72, { f: this.deg(n, 1), ratio: 3.5, index: 0.6, d: 0.7, vol: 0.045 }));
    v.done();
    this.duck(-4, 0.8, 0.6);
  }
  // Something unlocked or a new item for the book: "ta-da!". Discoveries can arrive in
  // runs (a new world full of new things), so it paces itself: the full fanfare at most
  // once per 3.5 s of quiet, and a light two-bell "ding-ding" (no music duck) in between.
  reward() {
    if (!this._live()) return;
    const now = this.ctx.currentTime, recent = now - this.lastReward < 3.5;
    this.lastReward = now;
    if (recent) {
      if (now - this.lastDing < 0.35) return;
      this.lastDing = now;
      const t = now + 0.005, v = new Voice(this, t, { kind: 'reward', send: 0.25, gain: dbToGain(-4) });
      [3, 5].forEach((n, j) => bell(this, v, t + j * 0.08, { f: this.deg(n), ratio: 3.5, index: 0.6, d: 0.5, vol: 0.09 }));
      v.done();
      return;
    }
    const t = now + 0.005, v = new Voice(this, t, { kind: 'reward', send: 0.22 });
    [2, 3, 4].forEach((n, j) => osc(this, v, t + j * 0.07, { type: 'triangle', f: this.deg(n), a: 0.005, d: 0.16, vol: 0.09, lp: 4000 }));
    const c0 = t + 0.24;
    for (const n of [0, 2, 3, 5]) {
      pad(this, v, c0, { f: this.deg(n), a: 0.02, hold: 0.2, d: 1.0, vol: 0.07, lp: 3400 });
      bell(this, v, c0, { f: this.deg(n, 1), ratio: 3.5, index: 0.6, d: 0.9, vol: 0.035 });
    }
    osc(this, v, c0, { type: 'triangle', f: this.deg(0, -2), a: 0.01, d: 0.8, vol: 0.13, lp: 600 });
    v.done();
    this._sparkle(c0 + 0.1, 1);
    this.duck(-7, 1.0, 0.7);
  }
}

// ------------------------------------------------------------------ helpers
function comp(c, o) {
  const n = c.createDynamicsCompressor();
  n.threshold.value = o.threshold; n.knee.value = o.knee; n.ratio.value = o.ratio;
  n.attack.value = o.attack; n.release.value = o.release;
  return n;
}
// The Web Audio DynamicsCompressor adds automatic makeup gain: (1 / curve(0 dBFS))^0.6
// (Blink/WebKit DynamicsCompressorKernel). We cancel it so the comps only ever turn
// things DOWN and the gain staging stays exactly as designed.
function makeupGain(o) {
  const lin = (d) => Math.pow(10, d / 20), dbl = (x) => 20 * Math.log10(x);
  const T = o.threshold, K = o.knee, R = o.ratio, lt = lin(T);
  const knee = (x, k) => (x < lt ? x : lt + (1 - Math.exp(-k * (x - lt))) / k);
  const slopeAt = (x, k) => {
    if (x < lt) return 1;
    const x2 = x * 1.001;
    return (dbl(knee(x2, k)) - dbl(knee(x, k))) / (dbl(x2) - dbl(x));
  };
  let lo = 0.1, hi = 10000, k = 5;
  const xk = lin(T + K);
  for (let i = 0; i < 15; i++) { if (slopeAt(xk, k) < 1 / R) hi = k; else lo = k; k = Math.sqrt(lo * hi); }
  const kneeDb = T + K, yKneeDb = dbl(knee(lin(kneeDb), k));
  const full = 1 < lin(kneeDb) ? knee(1, k) : lin(yKneeDb + (0 - kneeDb) / R);
  return Math.pow(1 / full, 0.6);
}
// Equal-power fades as short linear segments (never throws on overlapping automation).
const RAMP_N = 12;
function rampShape(fd, x) { // x in 0..1 at a segment boundary
  return fd.fadeIn ? fd.from + (fd.to - fd.from) * Math.sin(x * Math.PI / 2) : fd.to + (fd.from - fd.to) * Math.cos(x * Math.PI / 2);
}
function rampCurve(p, fd) {
  p.cancelScheduledValues(fd.t0);
  p.setValueAtTime(fd.from, fd.t0);
  for (let i = 1; i <= RAMP_N; i++) p.linearRampToValueAtTime(rampShape(fd, i / RAMP_N), fd.t0 + fd.dur * (i / RAMP_N));
}
// The value a rampCurve has reached at time t (same piecewise-linear shape the browser plays).
function curveValue(fd, t) {
  if (!fd) return 0;
  const x = clamp((t - fd.t0) / fd.dur, 0, 1) * RAMP_N, i = Math.floor(x);
  if (i >= RAMP_N) return rampShape(fd, 1);
  const a = rampShape(fd, i / RAMP_N), b = rampShape(fd, (i + 1) / RAMP_N);
  return a + (b - a) * (x - i);
}
function noiseBuffer(c, pink, rng = Math.random) {
  const n = Math.floor(c.sampleRate * 1.5), b = c.createBuffer(1, n, c.sampleRate), d = b.getChannelData(0);
  let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
  for (let i = 0; i < n; i++) {
    const w = rng() * 2 - 1;
    if (!pink) { d[i] = w; continue; }
    // Paul Kellet's pink filter
    b0 = 0.99886 * b0 + w * 0.0555179; b1 = 0.99332 * b1 + w * 0.0750759; b2 = 0.969 * b2 + w * 0.153852;
    b3 = 0.8665 * b3 + w * 0.3104856; b4 = 0.55 * b4 + w * 0.5329522; b5 = -0.7616 * b5 - w * 0.016898;
    d[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + w * 0.5362) * 0.11; b6 = w * 0.115926;
  }
  return b;
}
// A small, bright room: a few early reflections + a 0.9 s decaying stereo tail whose
// highs die faster (air absorption). Procedural DSP, no recorded impulse.
function roomIR(c, rng = Math.random) {
  const sr = c.sampleRate, len = Math.floor(sr * 0.95), ir = c.createBuffer(2, len, sr);
  const pre = Math.floor(sr * 0.012);
  for (let ch = 0; ch < 2; ch++) {
    const d = ir.getChannelData(ch);
    let lp = 0;
    for (let i = pre; i < len; i++) {
      const tt = (i - pre) / sr;
      const a = Math.exp(-tt * 6.9 / 0.85);              // RT60 about 0.85 s
      const cut = 0.55 * Math.exp(-tt * 3) + 0.05;       // one-pole coefficient falls: darker tail
      lp += cut * ((rng() * 2 - 1) - lp);
      d[i] = lp * a;
    }
    [0.007, 0.011, 0.017, 0.023, 0.031].forEach((s, j) => {
      const i = pre + Math.floor((s + ch * 0.0013 * (j + 1)) * sr);
      if (i < len) d[i] += (j % 2 ? -1 : 1) * 0.5 * Math.pow(0.8, j);
    });
  }
  let e = 0; // normalize energy so the send level means what it says
  for (let ch = 0; ch < 2; ch++) { const d = ir.getChannelData(ch); for (let i = 0; i < len; i++) e += d[i] * d[i]; }
  const s = 1 / Math.sqrt(e / 2);
  for (let ch = 0; ch < 2; ch++) { const d = ir.getChannelData(ch); for (let i = 0; i < len; i++) d[i] *= s * 0.5; }
  return ir;
}
